export const siteConfig = {
  name: 'FOOD PACK',
  fullName: 'Emballages alimentaires & Bouteilles de jus',
  slogan: 'L’emballage professionnel au service de vos saveurs et créations.',
  description: 'Food Pack fournit aux restaurateurs, traiteurs, producteurs de jus, bars à bissap et particuliers des emballages de qualité, bouteilles PET cristal, barquettes et boîtes kraft.',
  whatsapp: '2290100000000',
  phone: '+229 01 00 00 00 00',
  email: 'contact@foodpack.com',
  address: 'Cotonou, Bénin',
  instagram: 'https://instagram.com',
  facebook: 'https://facebook.com',
  currency: 'XOF',
  delivery: 'Livraison express à Cotonou, Calavi et expédition dans tout le Bénin.',
  deliveryFee: 2000,
}
