-- ====================================================================
-- 📦 SCHEMA SUPABASE COMPLET : FOOD PACK (EMBALLAGES ALIMENTAIRES)
-- ====================================================================

create extension if not exists "pgcrypto";

-- 1. NETTOYAGE COMPLET POUR REPARTIR DE ZÉRO
drop table if exists public.admin_notifications cascade;
drop table if exists public.traffic_logs cascade;
drop table if exists public.page_visits cascade;
drop table if exists public.order_items cascade;
drop table if exists public.orders cascade;
drop table if exists public.reviews cascade;
drop table if exists public.promo_codes cascade;
drop table if exists public.product_images cascade;
drop table if exists public.products cascade;
drop table if exists public.categories cascade;
drop table if exists public.gallery_items cascade;
drop table if exists public.testimonials cascade;
drop table if exists public.newsletter_subscribers cascade;
drop table if exists public.site_settings cascade;
drop table if exists public.site_content cascade;
drop table if exists public.profiles cascade;

-- 2. TYPES & ENUMS
drop type if exists public.user_role cascade;
create type public.user_role as enum ('admin', 'customer');

drop type if exists public.order_status cascade;
create type public.order_status as enum ('new', 'confirmed', 'in_progress', 'ready', 'delivered', 'cancelled');

-- 3. PROFILES (Comptes utilisateurs & Administrateurs)
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  role public.user_role not null default 'customer',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 4. CATÉGORIES
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  image_url text,
  description text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 5. PRODUITS D'EMBALLAGE
create table public.products (
  id bigint generated by default as identity primary key,
  category_id bigint references public.categories(id) on delete set null,
  name text not null,
  slug text not null unique,
  short_description text,
  description text,
  price integer not null check (price >= 0),
  old_price integer check (old_price is null or old_price >= price),
  rating numeric(3,1) not null default 5.0 check (rating >= 1.0 and rating <= 5.0),
  rating_count integer not null default 0,
  formats text[] not null default '{}',       -- Ex: ['Lot de 50', 'Carton de 500', 'Carton de 1000']
  capacities text[] not null default '{}',    -- Ex: ['250 ml', '330 ml', '500 ml', '1 L']
  materials text,                             -- Ex: 'PET transparent recyclable', 'Carton Kraft ingraissable'
  stock_status text not null default 'Disponible', -- 'Disponible', 'Sur commande', 'Rupture'
  featured boolean not null default false,
  new_arrival boolean not null default false,
  top_selling boolean not null default false,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 6. IMAGES & VIDÉOS DES PRODUITS
create table public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  url text not null,
  alt_text text,
  media_type text not null default 'image',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

-- 7. AVIS CLIENTS (Rating & Reviews)
create table public.reviews (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete cascade,
  customer_name text not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  comment text not null,
  is_verified boolean not null default true,
  created_at timestamptz not null default now()
);

-- 8. CODES PROMO
create table public.promo_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  discount_percent integer not null check (discount_percent > 0 and discount_percent <= 100),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- 9. COMMANDES (Orders)
create table public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique default ('EMB-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8))),
  customer_name text not null,
  phone text not null,
  city text not null,
  address text not null,
  delivery_method text not null,
  customer_comment text,
  promo_code text,
  discount_amount integer not null default 0 check (discount_amount >= 0),
  subtotal integer not null check (subtotal >= 0),
  delivery_fee integer not null default 0 check (delivery_fee >= 0),
  total integer not null check (total >= 0),
  status public.order_status not null default 'new',
  whatsapp_sent boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 10. ARTICLES DE COMMANDE
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  product_slug text,
  image_url text,
  unit_price integer not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0),
  format text,
  capacity text,
  note text
);

-- 11. NEWSLETTER
create table public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default now()
);

-- 12. PARAMÈTRES DU SITE
create table public.site_settings (
  id boolean primary key default true check (id),
  shop_name text not null default 'FOOD PACK',
  full_name text not null default 'Emballages alimentaires & Bouteilles de jus',
  slogan text not null default 'Des emballages de qualité professionnelle pour vos boissons et préparations.',
  whatsapp text default '2290100000000',
  phone text default '+229 01 00 00 00 00',
  email text default 'contact@foodpack.com',
  address text default 'Cotonou, Bénin',
  instagram text default 'https://instagram.com',
  facebook text default 'https://facebook.com',
  tiktok text default 'https://tiktok.com',
  delivery_fee integer not null default 2000,
  banner_text text default 'Inscrivez-vous et profitez de nos offres professionnelles !',
  updated_at timestamptz not null default now()
);

-- 13. CONTENUS DU SITE
create table public.site_content (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

-- 14. GALERIE & RÉALISATIONS
create table public.gallery_items (
  id bigint generated by default as identity primary key,
  title text not null,
  image_url text not null,
  category text,
  media_type text not null default 'image',
  sort_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now()
);

-- 15. TÉMOIGNAGES
create table public.testimonials (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  city text,
  content text not null,
  sort_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now()
);

-- 16. JOURNAL DE TRAFIC & STATISTIQUES
create table public.traffic_logs (
  id bigint generated by default as identity primary key,
  path text not null,
  user_agent text,
  created_at timestamptz not null default now()
);
create index if not exists traffic_logs_created_at_idx on public.traffic_logs (created_at desc);

-- 17. NOTIFICATIONS ADMINISTRATEUR
create table public.admin_notifications (
  id bigint generated by default as identity primary key,
  type text not null default 'info',
  title text not null,
  message text not null,
  target_path text,
  metadata jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists admin_notifications_created_at_idx on public.admin_notifications (created_at desc);
create index if not exists admin_notifications_unread_idx on public.admin_notifications (created_at desc) where read_at is null;

-- ====================================================================
-- 🔒 SÉCURITÉ : ROW LEVEL SECURITY (RLS) & POLITIQUES
-- ====================================================================

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.reviews enable row level security;
alter table public.promo_codes enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.site_settings enable row level security;
alter table public.site_content enable row level security;
alter table public.gallery_items enable row level security;
alter table public.testimonials enable row level security;
alter table public.traffic_logs enable row level security;
alter table public.admin_notifications enable row level security;

-- Fonction utilitaire Admin
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- Trigger création automatique profil
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.email),
    'customer'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Trigger notification admin lors d'une nouvelle commande
create or replace function public.notify_admins_of_new_order()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.admin_notifications (type, title, message, target_path, metadata)
  values (
    'new_order',
    'Nouvelle commande',
    new.customer_name || ' a passé la commande ' || new.order_number || ' (' || new.total || ' FCFA).',
    '/admin/commandes',
    jsonb_build_object('order_id', new.id, 'order_number', new.order_number, 'total', new.total)
  );
  return new;
end;
$$;

drop trigger if exists notify_admins_after_order_insert on public.orders;
create trigger notify_admins_after_order_insert
  after insert on public.orders
  for each row execute procedure public.notify_admins_of_new_order();

-- Politiques de lecture publique
create policy "Lecture publique des catégories actives" on public.categories for select using (is_active = true or public.is_admin());
create policy "Lecture publique des produits publiés" on public.products for select using (is_published = true or public.is_admin());
create policy "Lecture publique des images" on public.product_images for select using (true);
create policy "Lecture publique des avis" on public.reviews for select using (true);
create policy "Lecture publique des codes promo actifs" on public.promo_codes for select using (is_active = true or public.is_admin());
create policy "Lecture publique des paramètres" on public.site_settings for select using (true);
create policy "Lecture publique du contenu" on public.site_content for select using (true);
create policy "Lecture publique de la galerie" on public.gallery_items for select using (is_published = true or public.is_admin());
create policy "Lecture publique des témoignages" on public.testimonials for select using (is_published = true or public.is_admin());

-- Politiques d'insertion publique
create policy "Création publique de commandes" on public.orders for insert with check (true);
create policy "Création publique des articles de commande" on public.order_items for insert with check (true);
create policy "Création publique des avis clients" on public.reviews for insert with check (true);
create policy "Inscription newsletter publique" on public.newsletter_subscribers for insert with check (true);
create policy "Enregistrement anonyme du trafic" on public.traffic_logs for insert with check (true);

-- Politiques Administrateur (Accès total)
create policy "Admin total categories" on public.categories for all using (public.is_admin());
create policy "Admin total products" on public.products for all using (public.is_admin());
create policy "Admin total product_images" on public.product_images for all using (public.is_admin());
create policy "Admin total reviews" on public.reviews for all using (public.is_admin());
create policy "Admin total promo_codes" on public.promo_codes for all using (public.is_admin());
create policy "Admin total orders" on public.orders for all using (public.is_admin());
create policy "Admin total order_items" on public.order_items for all using (public.is_admin());
create policy "Admin total newsletter" on public.newsletter_subscribers for all using (public.is_admin());
create policy "Admin total settings" on public.site_settings for all using (public.is_admin());
create policy "Admin total content" on public.site_content for all using (public.is_admin());
create policy "Admin total gallery" on public.gallery_items for all using (public.is_admin());
create policy "Admin total testimonials" on public.testimonials for all using (public.is_admin());
create policy "Admin total profiles" on public.profiles for all using (public.is_admin() or id = auth.uid());
create policy "Admin total traffic" on public.traffic_logs for select using (public.is_admin());
create policy "Admin total notifications" on public.admin_notifications for all using (public.is_admin());

-- ====================================================================
-- 📦 STORAGE BUCKET (Images & Médias)
-- ====================================================================

insert into storage.buckets (id, name, public)
values ('catalog', 'catalog', true)
on conflict (id) do nothing;

drop policy if exists "Lecture publique du bucket catalog" on storage.objects;
create policy "Lecture publique du bucket catalog" on storage.objects for select using (bucket_id = 'catalog');

drop policy if exists "Upload admin sur bucket catalog" on storage.objects;
create policy "Upload admin sur bucket catalog" on storage.objects for insert with check (bucket_id = 'catalog' and public.is_admin());

drop policy if exists "Modification admin sur bucket catalog" on storage.objects;
create policy "Modification admin sur bucket catalog" on storage.objects for update using (bucket_id = 'catalog' and public.is_admin());

drop policy if exists "Suppression admin sur bucket catalog" on storage.objects;
create policy "Suppression admin sur bucket catalog" on storage.objects for delete using (bucket_id = 'catalog' and public.is_admin());

-- ====================================================================
-- ⚡ SUPABASE REALTIME
-- ====================================================================

do $$
begin
  alter publication supabase_realtime add table public.orders;
  alter publication supabase_realtime add table public.admin_notifications;
exception
  when others then null;
end $$;

-- ====================================================================
-- 🌱 DONNÉES INITIALES (SEED CATALOGUE EMBALLAGES)
-- ====================================================================

insert into public.site_settings (id, shop_name, full_name, slogan, whatsapp, phone, email, address, delivery_fee)
values (true, 'FOOD PACK', 'Boutique d’Emballages Alimentaires & Bouteilles de Jus', 'Vos emballages alimentaires et contenants de jus au meilleur prix à Cotonou.', '2290100000000', '+229 01 00 00 00 00', 'contact@foodpack.com', 'Cotonou, Bénin', 2000)
on conflict (id) do update set
  shop_name = excluded.shop_name,
  full_name = excluded.full_name,
  slogan = excluded.slogan;

-- Catégories
insert into public.categories (id, name, slug, description, sort_order)
values
  (1, 'Jus & Boissons (Bissap)', 'jus-boissons', 'Bouteilles PET cristal et bidons avec bouchons sécurisés pour bissap, baobab, gingembre et cocktails.', 1),
  (2, 'Emballages Kraft', 'emballages-kraft', 'Boîtes repas étanches, sacs kraft à poignées et sachets Doypack fenêtrés.', 2),
  (3, 'Plats & Barquettes Jetables', 'plats-barquettes', 'Barquettes aluminium, barquettes micro-ondables et bols salades avec couvercles.', 3),
  (4, 'Gobelets & Pâtisserie', 'gobelets-patisserie', 'Gobelets smoothie dôme, boîtes pâtissières avec fenêtre et pots desserts.', 4),
  (5, 'Accessoires & Couverts', 'accessoires-couverts', 'Kits couverts bois, serviettes, paille papier et papier ingraissable.', 5);

-- Codes Promo
insert into public.promo_codes (code, discount_percent, is_active)
values
  ('BIENVENUE10', 10, true),
  ('PACKPRO20', 20, true);

-- Produits Emballages réels
insert into public.products (id, category_id, name, slug, short_description, description, price, old_price, rating, rating_count, formats, capacities, materials, featured, new_arrival, top_selling)
values
  (1, 1, 'Bouteille PET Cristal à Jus / Bissap + Bouchon de sécurité', 'bouteille-pet-cristal-jus-bissap', 'Bouteille transparente rigide avec bouchon inviolable, idéale pour bissap, jus frais et sirops.', 'Fabriquée en PET transparent de haute qualité alimentaire. Le bouchon avec bague de sécurité assure une étanchéité totale et garantit la fraîcheur de vos boissons.', 6500, 7500, 4.8, 42, array['Lot de 50', 'Lot de 100', 'Carton de 250'], array['250 ml', '330 ml', '500 ml', '1 Litre'], 'PET alimentaire transparent recyclable', true, true, true),
  
  (2, 1, 'Bidon Alimentaire avec Poignée & Bouchon étanche', 'bidon-alimentaire-poignee', 'Bidon blanc opaque ou translucide pour gros volumes de bissap, jus et huiles.', 'Idéal pour les traiteurs et la vente de jus en gros format. Poignée ergonomique renforcée et bouchon hermétique anti-fuite.', 12000, 14000, 4.9, 18, array['Lot de 10', 'Lot de 25', 'Lot de 50'], array['1 Litre', '2 Litres', '5 Litres'], 'PEHD rigide haute densité', true, false, true),
  
  (3, 2, 'Boîte Repas Kraft Étanche Anti-graisse', 'boite-repas-kraft-etanche', 'Boîte kraft alimentaire à fermeture clapet intégrée pour plats chauds et froids.', 'Parfaite pour les livraisons de riz, grillades, pâtes et plats en sauce. Doublure intérieure anti-graisse ultra résistante.', 11500, 13000, 4.7, 35, array['Lot de 50', 'Lot de 100', 'Carton de 500'], array['500 ml', '750 ml', '1000 ml', '1500 ml'], 'Carton Kraft naturel avec barrière PE', true, true, true),
  
  (4, 2, 'Sac Papier Kraft à Poignées Torsadées', 'sac-papier-kraft-poignees', 'Sac cabas kraft ultra résistant pour transporter vos commandes repas et bouteilles.', 'Fond large pour maintenir les boîtes et bidons bien droits. Poignées torsadées renforcées.', 9500, 11000, 4.6, 29, array['Lot de 50', 'Lot de 100', 'Lot de 250'], array['Petit (22x10x28)', 'Moyen (26x14x32)', 'Grand (32x17x42)'], 'Papier Kraft résistant 90g/m²', false, true, true),
  
  (5, 3, 'Barquette Micro-ondable Noire + Couvercle Transparent', 'barquette-micro-ondable-couvercle', 'Barquette hermétique micro-ondable 1 ou 2 compartiments pour plats chauds.', 'Permet à vos clients de réchauffer directement le plat au micro-ondes. Couvercle clipsable hermétique anti-débordement.', 14000, 16000, 4.9, 56, array['Lot de 50', 'Lot de 100', 'Carton de 300'], array['500 ml', '750 ml', '1000 ml', '2 Compartiments'], 'Polypropylène (PP) alimentaire micro-ondable', true, true, true),
  
  (6, 3, 'Barquette Aluminium Alimentaire avec Couvercle Carton', 'barquette-aluminium-couvercle', 'Barquette aluminium pour cuisson au four et maintien au chaud.', 'Conserve la chaleur de vos poissons braisés, viandes et gratins. Couvercle carton étanche inclus.', 13500, 15000, 4.5, 23, array['Lot de 50', 'Lot de 100', 'Carton de 500'], array['650 ml', '900 ml', '1500 ml'], 'Aluminium alimentaire pur', false, false, true),
  
  (7, 4, 'Gobelet Smoothie PET Transparent + Couvercle Dôme', 'gobelet-smoothie-pet-dome', 'Gobelet cristal pour milkshakes, jus pressés, bissap glacé et granités.', 'Transparence cristal mettant en valeur les couleurs de vos jus. Couvercle dôme avec trou pour paille.', 8500, 9500, 4.8, 31, array['Lot de 50', 'Lot de 100', 'Carton de 500'], array['350 ml', '500 ml'], 'PET cristal recyclable', true, true, false),
  
  (8, 2, 'Sachet Kraft Doypack Zippé avec Fenêtre Transparente', 'sachet-kraft-doypack-fenetre', 'Sachet refermable hermétique pour épices, tisanes, kinkeliba, gari et snacks.', 'Fermeture zip hermétique et fenêtre transparente pour admirer le contenu. Tient debout tout seul en rayon.', 8000, 9000, 4.7, 19, array['Lot de 50', 'Lot de 100', 'Lot de 500'], array['100 g', '250 g', '500 g', '1 kg'], 'Kraft naturel + doublure barrière fraîcheur', false, true, false);

-- Images des Produits
insert into public.product_images (product_id, url, alt_text, sort_order)
values
  (1, '/products/bouteille-pet.webp', 'Bouteille PET Cristal à Jus et Bissap', 0),
  (1, '/products/bidon-alimentaire.webp', 'Bouteille PET et bidon alimentaire', 1),
  (2, '/products/bidon-alimentaire.webp', 'Bidon Alimentaire avec Poignée', 0),
  (2, '/products/bouteille-pet.webp', 'Bidon et bouteille jus', 1),
  (3, '/products/boite-kraft.webp', 'Boîte Repas Kraft Étanche', 0),
  (3, '/products/sac-kraft.webp', 'Boîte repas et sac kraft', 1),
  (4, '/products/sac-kraft.webp', 'Sac Papier Kraft à Poignées Torsadées', 0),
  (4, '/products/boite-kraft.webp', 'Sac et boîtes kraft', 1),
  (5, '/products/barquette-micro.webp', 'Barquette Micro-ondable Noire avec Couvercle', 0),
  (5, '/products/barquette-alu.webp', 'Barquette micro-ondable et aluminium', 1),
  (6, '/products/barquette-alu.webp', 'Barquette Aluminium avec Couvercle Carton', 0),
  (6, '/products/barquette-micro.webp', 'Barquette aluminium alimentaire', 1),
  (7, '/products/gobelet-smoothie.webp', 'Gobelet Smoothie PET avec Couvercle Dôme', 0),
  (7, '/products/bouteille-pet.webp', 'Gobelet smoothie et bouteille jus', 1),
  (8, '/products/sachet-doypack.webp', 'Sachet Kraft Doypack avec Fenêtre', 0),
  (8, '/products/sac-kraft.webp', 'Sachet doypack et sac kraft', 1);

-- Avis clients exemples
insert into public.reviews (product_id, customer_name, rating, comment, is_verified)
values
  (1, 'Aïcha D.', 5, 'Les bouteilles de 330ml sont impeccables pour mon bissap et jus de baobab. Le bouchon avec bague de sécurité rassure mes clients !', true),
  (1, 'Kevin T.', 5, 'Livraison rapide sur Cotonou. Plastique très rigide et transparent, ne se déforme pas.', true),
  (3, 'Maison Traiteur Naya', 5, 'Les boîtes kraft 750ml ne fuient pas du tout avec les sauces. C’est exactement ce qu’il nous fallait.', true),
  (5, 'Marc O.', 4, 'Très bonnes barquettes pour nos livraisons de midi. Le micro-ondes fonctionne parfaitement.', true);

-- Témoignages
insert into public.testimonials (customer_name, city, content, sort_order)
values
  ('Aïcha B.', 'Cotonou', 'Les bouteilles de bissap et les boîtes repas kraft sont d’une qualité irréprochable. Livraison en 24h respectée.', 1),
  ('Maison Naya', 'Calavi', 'Nos gâteaux et plats à emporter sont sublimés par ces emballages. Le service client est très réactif.', 2),
  ('Kevin T.', 'Porto-Novo', 'Le meilleur rapport qualité/prix pour les bidons et gobelets de jus au Bénin.', 3);
